-- ================================================================
-- WebNotas JILIU | La Promesa  —  DDL Oracle
-- Adaptado desde SupabaseDDL.sql (PostgreSQL / Supabase)
-- ================================================================
--
-- DIFERENCIAS CLAVE RESPECTO AL DDL DE POSTGRESQL:
--
--  TIPOS DE DATO
--    bigserial / smallserial  -->  NUMBER(19/5) GENERATED BY DEFAULT AS IDENTITY
--    text                     -->  VARCHAR2(4000)
--    uuid                     -->  VARCHAR2(36)
--    timestamptz              -->  TIMESTAMP WITH TIME ZONE
--    numeric(p,s)             -->  NUMBER(p,s)
--    smallint / integer       -->  NUMBER(5) / NUMBER(10)
--    bigint                   -->  NUMBER(19)
--    bpchar(1)                -->  CHAR(1)
--    varchar(n)               -->  VARCHAR2(n)
--    now()                    -->  SYSTIMESTAMP
--
--  TABLAS RENOMBRADAS (palabras reservadas Oracle):
--    level  -->  nivel      (LEVEL es pseudocolumna de CONNECT BY)
--    group  -->  grupo      (GROUP es palabra reservada)
--    type   -->  tipo_rol   (TYPE se usa para objetos PL/SQL)
--
--  COLUMNAS RENOMBRADAS:
--    attendance.date           -->  attendance.fecha
--    evaluation_type.type      -->  evaluation_type.nombre
--    materias.class            -->  materias.materia
--    class.level               -->  class.id_nivel
--    course.level              -->  course.id_nivel
--
--  RESTRICCIONES NO SOPORTADAS EN ORACLE:
--    ON UPDATE CASCADE         -->  eliminado (Oracle no lo soporta)
--    ON DELETE RESTRICT        -->  eliminado (Oracle no permite borrar el padre
--                                  si hay hijos, que es el comportamiento default)
--
--  FUNCIONALIDADES EXCLUIDAS (específicas de Supabase/PostgreSQL):
--    RLS (Row Level Security)  -->  no existe en Oracle; usar Oracle VPD
--    auth.uid() / auth.users   -->  no existe; manejar desde la aplicación
--    CREATE EXTENSION pg_trgm  -->  no existe; Oracle Text cubre casos similares
--    CONCURRENTLY en índices   -->  no soportado en Oracle
--    IF NOT EXISTS             -->  manejado con bloques EXCEPTION
--
-- ================================================================


-- ================================================================
-- SECCIÓN 1: ELIMINAR TABLAS (en orden inverso de dependencia)
-- ================================================================

BEGIN EXECUTE IMMEDIATE 'DROP TABLE materias    CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE attendance  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE grades      CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE evaluation  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE class_teacher CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE class_group  CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE user_type   CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE user_history CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE evaluation_type CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE class        CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE grupo        CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE module       CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE users        CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE type     CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE course       CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE nivel        CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ================================================================
-- SECCIÓN 2: TABLAS
-- ================================================================

-- nivel (PostgreSQL: level — renombrado por ser palabra reservada Oracle)
CREATE TABLE nivel (
  id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(4000) NOT NULL
);

-- module
CREATE TABLE module (
  id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(4000) NOT NULL
);

-- grupo (PostgreSQL: group — renombrado por ser palabra reservada Oracle)
CREATE TABLE grupo (
  id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      VARCHAR2(4000) NOT NULL,
  id_module NUMBER(5)      NOT NULL,
  CONSTRAINT fk_grupo_module FOREIGN KEY (id_module) REFERENCES module(id)
);

-- course
CREATE TABLE course (
  id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name     NUMBER(5)  NOT NULL,   -- número de curso (ej. 1, 2, 3…)
  year     NUMBER(5)  NOT NULL,
  id_nivel NUMBER(10) NOT NULL,
  CONSTRAINT fk_course_nivel FOREIGN KEY (id_nivel) REFERENCES nivel(id)
);

-- class
CREATE TABLE class (
  id         NUMBER(19)               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR2(4000)           NOT NULL,
  id_nivel   NUMBER(10)               NOT NULL,
  created_at DATE DEFAULT SYSDATE,
  id_module  NUMBER(19)               NOT NULL,
  id_group   NUMBER(5)                NOT NULL,
  CONSTRAINT fk_class_nivel   FOREIGN KEY (id_nivel)  REFERENCES nivel(id),
  CONSTRAINT fk_class_module  FOREIGN KEY (id_module) REFERENCES module(id) ON DELETE CASCADE
);

-- class_group  (tabla puente clase ↔ grupo)
CREATE TABLE class_group (
  id_class NUMBER(19) NOT NULL,
  id_group NUMBER(19) NOT NULL,
  CONSTRAINT pk_class_group    PRIMARY KEY (id_class, id_group),
  CONSTRAINT fk_cg_class       FOREIGN KEY (id_class) REFERENCES class(id) ON DELETE CASCADE,
  CONSTRAINT fk_cg_grupo       FOREIGN KEY (id_group) REFERENCES grupo(id) ON DELETE CASCADE
);

-- evaluation_type
CREATE TABLE evaluation_type (
  id         NUMBER(19)               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     VARCHAR2(4000)           NOT NULL,   -- PostgreSQL: type
  created_at DATE DEFAULT SYSDATE,
  CONSTRAINT uq_evaluation_type_nombre UNIQUE (nombre)
);

-- type (PostgreSQL: type — renombrado para no conflicto con TYPE de PL/SQL)
-- roles: 'S' student, 'T' teacher, 'A' admin
CREATE TABLE type (
  id   NUMBER(5) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code CHAR(1)   NOT NULL,
  name VARCHAR2(4000) NOT NULL,
  CONSTRAINT uq_type_code  UNIQUE (code),
  CONSTRAINT chk_type_code CHECK (code IN ('S','T','A'))
);

INSERT INTO type (code, name) VALUES ('S', 'Student');
INSERT INTO type (code, name) VALUES ('T', 'Teacher');
INSERT INTO type (code, name) VALUES ('A', 'Admin');
COMMIT;

-- users
-- NOTA: En Supabase, users.id referencia auth.users (UUID de Supabase Auth).
--       En Oracle no existe esa tabla externa; id es la PK de la aplicación.
CREATE TABLE users (
  id         VARCHAR2(36)             NOT NULL PRIMARY KEY,  -- UUID generado por la app
  name       VARCHAR2(4000)           NOT NULL,
  email      VARCHAR2(4000)           NOT NULL,
  code_jiliu VARCHAR2(4000),          -- mapear ETM studentDescription -> code
  id_course  NUMBER(19),
  cedula     VARCHAR2(4000),
  created_at DATE DEFAULT SYSDATE,
  CONSTRAINT uq_users_email      UNIQUE (email),
  CONSTRAINT uq_users_code_jiliu UNIQUE (code_jiliu),
  CONSTRAINT uq_users_cedula     UNIQUE (cedula)
  -- FK a course se agrega después (course aún no referencia users)
);

-- Agregar FK de users a course (course ya existe en este punto)
ALTER TABLE users
  ADD CONSTRAINT fk_users_course FOREIGN KEY (id_course) REFERENCES course(id);

-- user_history
CREATE TABLE user_history (
  id_student VARCHAR2(36)             NOT NULL,
  id_course  NUMBER(19)               NOT NULL,
  created_at DATE DEFAULT SYSDATE,
  CONSTRAINT pk_user_history         PRIMARY KEY (id_student, id_course),
  CONSTRAINT fk_uh_student           FOREIGN KEY (id_student) REFERENCES users(id)   ON DELETE CASCADE,
  CONSTRAINT fk_uh_course            FOREIGN KEY (id_course)  REFERENCES course(id)  ON DELETE CASCADE
);

-- user_type
CREATE TABLE user_type (
  id_user    VARCHAR2(36)             NOT NULL,
  id_type    NUMBER(5)                NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_user_type            PRIMARY KEY (id_user, id_type),
  CONSTRAINT fk_ut_user              FOREIGN KEY (id_user) REFERENCES users(id)     ON DELETE CASCADE,
  CONSTRAINT fk_ut_tipo              FOREIGN KEY (id_type) REFERENCES type(id)
);

-- class_teacher  (relación profesor ↔ materia ↔ curso)
CREATE TABLE class_teacher (
  id_teacher VARCHAR2(36)             NOT NULL,
  id_class   NUMBER(19)               NOT NULL,
  created_at DATE DEFAULT SYSDATE,
  id_course  NUMBER(19),
  CONSTRAINT pk_class_teacher        PRIMARY KEY (id_teacher, id_class),
  CONSTRAINT fk_ct_teacher           FOREIGN KEY (id_teacher) REFERENCES users(id)   ON DELETE CASCADE,
  CONSTRAINT fk_ct_class             FOREIGN KEY (id_class)   REFERENCES class(id)   ON DELETE CASCADE,
  CONSTRAINT fk_ct_course            FOREIGN KEY (id_course)  REFERENCES course(id)  ON DELETE CASCADE
);

-- evaluation
CREATE TABLE evaluation (
  id         NUMBER(19)               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_course  NUMBER(19),
  id_class   NUMBER(19),
  id_teacher VARCHAR2(36)             NOT NULL,
  id_type    NUMBER(19)               NOT NULL,
  percent    NUMBER(5,2)              NOT NULL,
  title      VARCHAR2(4000)           DEFAULT 'Evaluación' NOT NULL,
  created_at DATE DEFAULT SYSDATE,
  id_group   NUMBER(19)               NOT NULL,
  id_module  NUMBER(19)               NOT NULL,
  CONSTRAINT chk_eval_percent        CHECK (percent >= 0 AND percent <= 100),
  CONSTRAINT fk_eval_course          FOREIGN KEY (id_course)  REFERENCES course(id)         ON DELETE CASCADE,
  CONSTRAINT fk_eval_class           FOREIGN KEY (id_class)   REFERENCES class(id)          ON DELETE CASCADE,
  CONSTRAINT fk_eval_teacher         FOREIGN KEY (id_teacher) REFERENCES users(id)          ON DELETE CASCADE,
  CONSTRAINT fk_eval_type            FOREIGN KEY (id_type)    REFERENCES evaluation_type(id),
  CONSTRAINT fk_eval_group           FOREIGN KEY (id_group)   REFERENCES grupo(id)          ON DELETE CASCADE,
  CONSTRAINT fk_eval_module          FOREIGN KEY (id_module)  REFERENCES module(id)         ON DELETE CASCADE
);

-- grades  (nota por estudiante por evaluación)
CREATE TABLE grades (
  id_student  VARCHAR2(36)            NOT NULL,
  id_exam     NUMBER(19)              NOT NULL,
  grade       NUMBER(10,2)            NOT NULL,
  finished_at DATE,
  attempts    NUMBER(10)              DEFAULT 1 NOT NULL,
  created_at  DATE DEFAULT SYSDATE,
  updated_at  DATE DEFAULT SYSDATE,
  CONSTRAINT pk_grades               PRIMARY KEY (id_student, id_exam),
  CONSTRAINT fk_grades_student       FOREIGN KEY (id_student) REFERENCES users(id)      ON DELETE CASCADE,
  CONSTRAINT fk_grades_exam          FOREIGN KEY (id_exam)    REFERENCES evaluation(id) ON DELETE CASCADE
);

-- attendance  (asistencia)
-- NOTA: columna "date" renombrada a "fecha" (DATE es tipo de dato en Oracle)
CREATE TABLE attendance (
  id         NUMBER(19)               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_student VARCHAR2(36)             NOT NULL,
  id_class   NUMBER(19)               NOT NULL,
  fecha      DATE DEFAULT SYSDATE,  -- PostgreSQL: date
  observation VARCHAR2(4000),
  CONSTRAINT fk_att_student          FOREIGN KEY (id_student) REFERENCES users(id)  ON DELETE CASCADE,
  CONSTRAINT fk_att_class            FOREIGN KEY (id_class)   REFERENCES class(id)  ON DELETE CASCADE
);

-- materias  (tabla de referencia normalizada nivel → módulo → grupo → materia)
CREATE TABLE materias (
  id_module NUMBER(10)    NOT NULL,
  module    VARCHAR2(300) NOT NULL,
  id_group  NUMBER(10)    NOT NULL,
  grupo     VARCHAR2(300) NOT NULL,
  id_class  NUMBER(10)    NOT NULL,
  materia   VARCHAR2(300) NOT NULL,   -- PostgreSQL: class
  id_nivel  NUMBER(10)    NOT NULL,   -- PostgreSQL: level
  CONSTRAINT pk_materias PRIMARY KEY (id_class)
);


-- ================================================================
-- SECCIÓN 3: ÍNDICES
-- ================================================================

-- class_group
CREATE UNIQUE INDEX idx_class_group_uq       ON class_group  (id_class, id_group);
CREATE INDEX idx_class_group_id_group        ON class_group  (id_group);

-- class
CREATE INDEX idx_class_id_module             ON class        (id_module);
CREATE INDEX idx_class_nivel_name            ON class        (id_nivel, name);

-- users
CREATE INDEX idx_users_id_course_name        ON users        (id_course, name);

-- class_teacher
CREATE INDEX idx_class_teacher_id_class      ON class_teacher (id_class);

-- user_history
CREATE INDEX idx_user_history_id_course      ON user_history  (id_course);

-- user_type
CREATE INDEX idx_user_type_user              ON user_type     (id_user);
CREATE INDEX idx_user_type_type              ON user_type     (id_type);

-- evaluation
CREATE INDEX idx_eval_teacher_created        ON evaluation    (id_teacher, created_at DESC);
CREATE INDEX idx_eval_course_class_created   ON evaluation    (id_course, id_class, created_at ASC, id ASC);
CREATE INDEX idx_eval_class_created          ON evaluation    (id_class, created_at ASC, id ASC);


-- ================================================================
-- SECCIÓN 4: TRIGGER  (equivalente a trg_grades_updated_at)
-- ================================================================

CREATE OR REPLACE TRIGGER trg_grades_updated_at
BEFORE UPDATE ON grades
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSDATE;
END;
/
